### ISSUE TITLE
REL: can I get a new release

### ISSUE THREAD

**Issue by CJ-Wright** [diffpy/libobjcryst#5]
I need the python3 friendly scons stuff.

**Comment by pavoljuhas** [comment]
Last time I checked scons was only available for Python 2.  libobjcryst is a C++ only library - you can build it with any scons, even one outside of conda, and the produced library would link with pyobjcryst for either of Python 2 or 3.  The libobjryst conda package is built in a Python 2.7 environment because of scons, but it has no Python dependency and can be installed to either of 2.7 or 3.X environments.

Please, describe your use case in more detail if this does not answer your question.

**Comment by CJ-Wright** [comment]
Scons now supports python 3 http://scons.org/scons-300-is-available.html
There is a conda-forge recipe for scons with python 3 https://anaconda.org/conda-forge/scons/files?channel=main
I am trying to put this on conda-forge and have a python 3 build so having a new release that was python 3 friendly (which I think is already in master) would be awesome.

**Comment by pavoljuhas** [comment]
Can you do conda-forge build with a Python 2 scons for now?  As I said, the output package is Python independent and it should not matter what environment and what scons version are used to build it.

That said, we of course want the scons scripts to work with the latest scons.
Do you get any PY3-related errors when running scons-3?

**Comment by pavoljuhas** [comment]
scons is required only at the build stage, but not at the run stage.  The libobjcryst package has [no runtime dependencies](https://github.com/diffpy/libobjcryst/blob/5f9e024e384cc7bcfbb236f6909112b8cfd9789c/conda-recipe/meta.yaml#L14-L18) as it only links with the system C++ libraries.

> Yes, the current version has some print statements without parens in the scons files for lbobjcryst ...

That is in the last release v2017.1.1.  Can you test scons-3 with the current master?

**Comment by CJ-Wright** [comment]
Usually conda-forge does not build against master, and I'd rather not build this on my current machine. If the system is going to support python 3 then maybe Travis should test against it?

**Comment by CJ-Wright** [comment]
It seems that `ConfigParser` is referenced [here](https://github.com/diffpy/libobjcryst/blob/7a7dc8c4a214109777c42561417eaa57d8958903/site_scons/libobjcrystbuildutils.py#L60) which is not supported in python3

**Comment by pavoljuhas** [comment]
> Can we have Travis try a build with conda scons?

In my experience it is much faster to debug builds on a local machine.  If your computer does not work, why don't you test build on romaioi (install miniconda within your account) or on an AWS Linux instance?

> It seems that ConfigParser is referenced here which is not supported in python3.

OK - can you please create a new issue for that with a descriptive topic such as `support scons 3` or similar?

**Comment by CJ-Wright** [comment]
I wasn't expecting this to be this painful.

**Comment by pavoljuhas** [comment]
Eh - there is a zero-effort solution for your conda-forge build by using Python 2 scons.  If you insist on Python 3 scons, that's what you get.  :-)

**Comment by pavoljuhas** [comment]
out of date.
